### ISSUE TITLE
[repo triage] simple-web-worker

### ISSUE THREAD

**Issue by Rumyra** [mdn/content-team-projects#27]
- [x] triage prs
- [x] triage issues
- [x] add contribution doc
- [x] add any notes about repo to readme
- [x] change master to main
- [x] move if necessary
- [x] update urls in content
- [ ] archive repo if necessary
- [x] add to motherboard project

**Comment by schalkneethling** [comment]
This has been moved and archived - https://github.com/mdn/simple-web-worker
