### ISSUE TITLE
[Repo] Move web-speech-api into dom-examples

### ISSUE THREAD

**Issue by Rumyra** [mdn/content-team-projects#49]
https://github.com/mdn/web-speech-api
- [x] triage prs - 5
- [x] triage issues - 27
- [ ] add contribution doc
- [x] add any notes about repo to readme
- [x] change master to main
- [x] move if necessary - create new folder
- [ ] update urls in content
- [x] archive repo if necessary
- [ ] add to motherboard project

**Comment by schalkneethling** [comment]
down to 13 issues and 1 pull request.

**Comment by MrBrain295** [comment]
All the links in content will be fixed when mdn/content#17471 is merged.

**Comment by Rumyra** [comment]
Cool 🎉
